// ==================== AUDIO MANAGER ====================
// Music (Lyria 3), SFX (ElevenLabs), and voice lines (Cartesia) generated by
// scripts/generate_assets.py. Voice falls back to browser speech if a file is missing.

const AUDIO_BASE = '../assets/audio/signpost-sleuth';
const MUSIC_KEYS = ['menu', 'story', 'speed', 'quiz', 'victory'];
const SFX_KEYS = ['tap', 'stop', 'correct', 'wrong', 'stamp', 'page', 'sticky', 'whoosh', 'fanfare'];

class AudioManager {
  constructor() {
    this.music = {};
    this.currentMusic = null;
    this.musicVolume = 0.3;
    this.sfxVolume = 0.7;
    this.voiceVolume = 1.0;
    const prefs = this._loadPrefs();
    this.musicEnabled = prefs.music !== false;
    this.sfxEnabled = true;
    this.voiceEnabled = prefs.voice !== false;
    this.sfxPool = {};
    this.voiceEl = null;
    this.missingVoice = new Set();
    this.unlocked = false;
  }

  _loadPrefs() {
    try { return JSON.parse(localStorage.getItem('ps_audio_prefs') || '{}'); } catch (_) { return {}; }
  }

  _savePrefs() {
    try { localStorage.setItem('ps_audio_prefs', JSON.stringify({ music: this.musicEnabled, voice: this.voiceEnabled })); } catch (_) {}
  }

  unlock() {
    if (this.unlocked) return;
    this.unlocked = true;
    MUSIC_KEYS.forEach(key => {
      const el = new Audio(`${AUDIO_BASE}/music/${key}.mp3`);
      el.preload = 'auto';
      el.loop = key !== 'victory';
      el.volume = this.musicVolume;
      this.music[key] = el;
    });
    // Without this, iOS mutes Web Audio when the ringer switch is on silent.
    try { if (navigator.audioSession) navigator.audioSession.type = 'playback'; } catch (_) {}
    const Ctx = window.AudioContext || window.webkitAudioContext;
    if (Ctx) {
      this.ctx = new Ctx();
      this.ctx.resume().catch(() => {});
      this.sfxBuffers = {};
      const wake = () => { if (this.ctx.state !== 'running') this.ctx.resume().catch(() => {}); };
      ['touchend', 'click', 'keydown'].forEach(ev => window.addEventListener(ev, wake, { passive: true }));
    }
    SFX_KEYS.forEach(key => {
      const url = `${AUDIO_BASE}/sfx/${key}.mp3`;
      if (this.ctx) {
        fetch(url)
          .then(r => r.arrayBuffer())
          .then(data => new Promise((res, rej) => this.ctx.decodeAudioData(data, res, rej)))
          .then(buf => { this.sfxBuffers[key] = buf; })
          .catch(() => {});
      }
      this.sfxPool[key] = [0, 1, 2].map(() => {
        const el = new Audio(url);
        el.preload = 'auto';
        return el;
      });
    });
    if (this.pendingMusic) this.playMusic(this.pendingMusic);
  }

  playMusic(key) {
    if (!this.unlocked) { this.pendingMusic = key; return; }
    const el = this.music[key];
    if (!el) return;
    if (this.currentMusic === key && !el.paused) return;
    if (this.currentMusic && this.music[this.currentMusic] && this.currentMusic !== key) {
      this.music[this.currentMusic].pause();
    }
    this.currentMusic = key;
    if (!this.musicEnabled) return;
    el.currentTime = 0;
    el.volume = this._duckedVolume();
    el.play().catch(() => {});
  }

  stopMusic() {
    if (this.currentMusic && this.music[this.currentMusic]) this.music[this.currentMusic].pause();
  }

  toggleMusic() {
    this.musicEnabled = !this.musicEnabled;
    if (!this.musicEnabled) this.stopMusic();
    else if (this.currentMusic) {
      const el = this.music[this.currentMusic];
      if (el) el.play().catch(() => {});
    }
    this._savePrefs();
    return this.musicEnabled;
  }

  toggleVoice() {
    this.voiceEnabled = !this.voiceEnabled;
    if (!this.voiceEnabled) this.stopVoice();
    this._savePrefs();
    return this.voiceEnabled;
  }

  sfx(key, { volume = 1, rate = 1 } = {}) {
    if (!this.sfxEnabled || !this.unlocked) return;
    const r = rate * (0.94 + Math.random() * 0.12);
    const buf = this.sfxBuffers && this.sfxBuffers[key];
    if (buf) {
      if (this.ctx.state === 'suspended') this.ctx.resume().catch(() => {});
      const src = this.ctx.createBufferSource();
      src.buffer = buf;
      src.playbackRate.value = r;
      const gain = this.ctx.createGain();
      gain.gain.value = Math.min(1, this.sfxVolume * volume);
      src.connect(gain).connect(this.ctx.destination);
      src.start();
      return;
    }
    const pool = this.sfxPool[key];
    if (!pool) return;
    const el = pool.find(a => a.paused || a.ended) || pool[0];
    try {
      el.currentTime = 0;
      el.volume = Math.min(1, this.sfxVolume * volume);
      el.playbackRate = r;
      el.play().catch(() => {});
    } catch (_) {}
  }

  _duckedVolume() {
    const speaking = this.voiceEl && !this.voiceEl.paused;
    return speaking ? this.musicVolume * 0.35 : this.musicVolume;
  }

  _applyDuck() {
    const el = this.currentMusic && this.music[this.currentMusic];
    if (el) el.volume = this._duckedVolume();
  }

  stopVoice() {
    if (this.voiceEl) { this.voiceEl.pause(); this.voiceEl = null; }
    if (window.speechSynthesis) window.speechSynthesis.cancel();
    this._applyDuck();
  }

  // key = voice file basename (e.g. 'n_welcome'); text = fallback for browser speech.
  // force = play even when auto-voice is off (the kid tapped a speaker button).
  say(key, text, { force = false } = {}) {
    if (!this.voiceEnabled && !force) return;
    this.stopVoice();
    if (key && !this.missingVoice.has(key)) {
      const el = new Audio(`${AUDIO_BASE}/voice/${key}.mp3`);
      el.volume = this.voiceVolume;
      this.voiceEl = el;
      el.onended = () => { if (this.voiceEl === el) this.voiceEl = null; this._applyDuck(); };
      el.onerror = () => {
        this.missingVoice.add(key);
        if (this.voiceEl === el) { this.voiceEl = null; this._speakFallback(text); }
      };
      el.play().then(() => this._applyDuck()).catch(() => {});
      return;
    }
    this._speakFallback(text);
  }

  _speakFallback(text) {
    if (!text || !window.speechSynthesis) return;
    const u = new SpeechSynthesisUtterance(text);
    u.rate = 0.95;
    u.pitch = 1.05;
    window.speechSynthesis.speak(u);
  }
}
