// ==================== STORIES + SPEED CARDS ====================
// Original short stories written for Signpost Sleuth. Each paragraph is a list of sentences.
// stops: signposts in that paragraph. "at" is the sentence index; "alt" are other sentences that also count.
// early: sentences that hint at an Again & Again signpost before (or after) it's caught. No penalty for tapping them.
// Everything after "window.PS_STORIES = " must stay valid JSON (parsed by generate_assets.py).
window.PS_STORIES = {
  "cases": [
    {
      "id": "chair",
      "title": "First Chair",
      "blurb": "Maya always sits in last chair in band. Will tryouts change that?",
      "bg": "band",
      "paragraphs": [
        { "s": ["Maya had played the flute since fourth grade, and she always sat in the very last chair.", "\"Last chair is safe,\" she liked to say.", "\"Nobody listens to last chair.\"", "Tryouts for first chair were on Friday, and everyone in band was talking about them."], "early": [1] },
        { "s": ["On Monday, Mr. Ortiz handed out the tryout music.", "It was a fast piece full of tricky runs.", "Maya's friend Jada groaned.", "\"I'm not even trying out,\" Maya said.", "\"Last chair is safe.\""], "early": [4] },
        { "s": ["That night Maya opened her flute case, and she remembered the first time she ever played for an audience.", "She was nine years old at the spring concert, and her hands shook so badly that her first note came out as a squeak.", "A few kids laughed.", "She had sat in the back of every band since."],
          "stops": [{ "type": "mm", "at": 0, "alt": [1],
            "why": "The story stops the action to tell us about something that happened when Maya was nine.",
            "note": { "a": "It explains why Maya hides in last chair: she's afraid people will laugh again.", "wrong": ["It tells us Maya's favorite song.", "It shows the band was too loud."] } }] },
        { "s": ["On Wednesday, Maya stayed after school to help put the music stands away.", "Mr. Ortiz was packing up his trumpet.", "\"You're trying out, right?\" he asked.", "Maya shook her head.", "Mr. Ortiz pulled up a chair next to her.", "\"Maya, I've been teaching for twenty years, and the players who grow the most are the ones who are willing to play a wrong note in front of people.\"", "\"Mistakes aren't the end of the music. They're part of it.\""],
          "stops": [{ "type": "ww", "at": 5, "alt": [4, 6],
            "why": "An older, wiser character takes Maya aside and gives her serious advice.",
            "note": { "a": "Making mistakes is part of getting better, so don't let fear stop you.", "wrong": ["Always help put the music stands away.", "Trumpets are better than flutes."] } }] },
        { "s": ["Walking home, Maya kept hearing his words.", "What if she tried out and squeaked again in front of everyone?", "Was it better to stay safe forever, or to risk looking silly?"],
          "stops": [{ "type": "tq", "at": 2, "alt": [1],
            "why": "Maya asks herself a really hard question that she doesn't know the answer to.",
            "note": { "a": "Will Maya be brave enough to try out, even though she's scared?", "wrong": ["What will Maya eat for dinner?", "How long is Maya's walk home?"] } }] },
        { "s": ["On Thursday, Jada found Maya in the practice room before school, playing the tryout piece over and over.", "\"I thought you weren't trying out,\" Jada said.", "\"Last chair is safe, remember?\"", "Maya just kept playing."],
          "stops": [
            { "type": "cc", "at": 0, "alt": [3],
              "why": "Maya said she wasn't trying out, but now she's practicing the tryout music. That's the opposite of what she's been saying.",
              "note": { "a": "Mr. Ortiz's advice is changing her mind, so she might try out after all.", "wrong": ["She is bored and has nothing else to do.", "Jada asked her to practice for her."] } },
            { "type": "aa", "at": 2, "alt": [],
              "why": "\"Last chair is safe\" has now shown up three times.",
              "note": { "a": "Staying \"safe\" is Maya's big problem. The story is about whether she'll stop hiding.", "wrong": ["The author forgot she already wrote it.", "Maya likes how the word safe sounds."] } }
          ] },
        { "s": ["On Friday, Maya walked to the front of the band room with her flute.", "Halfway through the piece, her finger slipped and a note squeaked.", "Nobody laughed.", "She took a breath and kept going, and suddenly she understood what Mr. Ortiz meant.", "The squeak didn't ruin anything. The music just kept going, and so could she."],
          "stops": [{ "type": "aha", "at": 3, "alt": [4],
            "why": "Maya suddenly understands something important. She figures out the life lesson.",
            "note": { "a": "Maya won't let the fear of mistakes keep her hiding anymore.", "wrong": ["Maya will quit band.", "Mr. Ortiz will buy a new trumpet."] } }] },
        { "s": ["Maya didn't get first chair.", "She got fourth.", "But when she sat down in her new seat, closer to the front than ever before, she grinned.", "Fourth chair wasn't safe at all.", "It was so much better."], "early": [3] }
      ]
    },
    {
      "id": "lighthouse",
      "title": "The Lighthouse Key",
      "blurb": "Grandpa Ray keeps the old lighthouse locked. Nora wants to know why.",
      "bg": "lighthouse",
      "paragraphs": [
        { "s": ["Nora spent every summer at her grandfather's house next to the old lighthouse.", "Grandpa Ray was a quiet man who fixed boats all day and hardly ever smiled.", "Nora loved the lighthouse, but it had been locked for as long as she could remember."] },
        { "s": ["On her first morning, Nora found a rusty brass key hanging on a nail in the kitchen.", "\"Don't touch that,\" Grandpa said without looking up from his coffee.", "\"That key stays on its nail.\""], "early": [0, 2] },
        { "s": ["All week, Nora noticed the key.", "It was there when she ate breakfast.", "It was there when she came in from the beach.", "Once, she saw Grandpa standing in front of it, just staring, while his coffee went cold."],
          "stops": [{ "type": "aa", "at": 0, "alt": [1, 2, 3],
            "why": "The brass key keeps showing up, over and over.",
            "note": { "a": "The key is important. It probably connects to a secret about Grandpa and the lighthouse.", "wrong": ["Nora wants to be a locksmith.", "The kitchen has a lot of nails."] } }] },
        { "s": ["One rainy afternoon, Nora asked, \"Grandpa, why is the lighthouse always locked?\"", "Grandpa put down his wrench and was quiet for a long time.", "Then he told her about a stormy night forty years ago, when Grandma climbed the lighthouse stairs and kept the lamp burning until every fishing boat made it home safely.", "\"After she passed away,\" he said, \"I couldn't stand to go up there.\""],
          "stops": [{ "type": "mm", "at": 2, "alt": [],
            "why": "The action stops so Grandpa can tell a memory from forty years ago.",
            "note": { "a": "The lighthouse means a lot to Grandpa because of Grandma. That's why he keeps it locked.", "wrong": ["It tells us it rains a lot by the ocean.", "It shows that fishing boats are slow."] } }] },
        { "s": ["That night, Nora couldn't sleep.", "Should she leave the lighthouse alone, the way Grandpa wanted?", "Or was it wrong to let something Grandma loved sit dark forever?"],
          "stops": [{ "type": "tq", "at": 2, "alt": [1],
            "why": "Nora asks herself a hard question with no easy answer.",
            "note": { "a": "Will Nora try to open the lighthouse, and how will Grandpa feel about it?", "wrong": ["What time will Nora wake up?", "Does the lighthouse need new paint?"] } }] },
        { "s": ["The next morning, old Mrs. Patel from next door was painting her fence when Nora walked by.", "Nora told her all about the key.", "Mrs. Patel set down her brush.", "\"Child, when we lose someone, we sometimes lock away the things that remind us of them,\" she said.", "\"But love isn't meant to be locked up.\""],
          "stops": [{ "type": "ww", "at": 3, "alt": [4],
            "why": "An older, wiser neighbor gives Nora serious advice about life.",
            "note": { "a": "Remembering the people we've lost can help us heal. Don't lock love away.", "wrong": ["Fences need fresh paint every summer.", "Don't talk to your neighbors."] } }] },
        { "s": ["When Nora got home, the key was gone from its nail.", "She ran outside and gasped.", "Grandpa was climbing the lighthouse stairs with the brass key in his hand, and he was humming."],
          "stops": [{ "type": "cc", "at": 2, "alt": [],
            "why": "Quiet Grandpa, who never goes up there, is climbing the stairs and humming. That's the opposite of how he's acted all along.",
            "note": { "a": "Grandpa might be ready to remember Grandma in a happy way instead of hiding from the memory.", "wrong": ["He needs to fix a boat up there.", "He is looking for his coffee."] } }], "early": [0] },
        { "s": ["Nora climbed up after him.", "At the top, Grandpa was polishing the big glass lamp.", "\"I thought that if I lit it, I'd miss her more,\" he said softly.", "\"But I just realized something.", "Keeping it dark never made me miss her less. Lighting it is how I remember her.\""],
          "stops": [{ "type": "aha", "at": 3, "alt": [4],
            "why": "Grandpa suddenly realizes something that changes how he feels.",
            "note": { "a": "Grandpa will light the lighthouse again and start to heal from his sadness.", "wrong": ["Grandpa will sell the lighthouse.", "Nora will go home early."] } }] },
        { "s": ["That night, for the first time in years, the lighthouse beam swept across the dark water.", "Grandpa stood next to Nora on the porch, and he smiled."] }
      ]
    },
    {
      "id": "newkid",
      "title": "Across the Street",
      "blurb": "I decided I didn't like the new girl. Then her sketchbook slid to my feet.",
      "bg": "school",
      "paragraphs": [
        { "s": ["When Priya moved into the house across the street, I decided right away that I didn't like her.", "She wore a fancy blazer on the first day of sixth grade, and she corrected Mr. Kim's spelling on the board.", "\"She thinks she's better than everyone,\" I told my best friend Leah at lunch."] },
        { "s": ["Priya carried a beat-up green sketchbook everywhere she went.", "She drew in it during homeroom.", "She drew in it at the bus stop.", "I figured it was full of drawings of how great she was."], "early": [0, 1, 2] },
        { "s": ["Then one day in science, Priya's green sketchbook fell off her desk and slid right to my feet.", "I picked it up, and it fell open to a drawing of a house with a big tree and a tire swing.", "Under it, she had written, \"Home. 847 miles away.\""],
          "stops": [{ "type": "aa", "at": 0, "alt": [1],
            "why": "The green sketchbook keeps showing up again and again.",
            "note": { "a": "It's a clue to who Priya really is. Maybe she misses her old home.", "wrong": ["Priya needs a new sketchbook.", "The science room floor is slippery."] } }] },
        { "s": ["Seeing that drawing reminded me of the summer I was seven, when we moved here from Ohio.", "I cried every night for a month.", "At my new school, I was so nervous that I acted tough, so nobody would know how scared I was."],
          "stops": [{ "type": "mm", "at": 0, "alt": [1, 2],
            "why": "The narrator stops the story to remember moving when she was seven.",
            "note": { "a": "She once acted tough because she was scared. Maybe Priya is acting \"fancy\" for the same reason.", "wrong": ["Ohio has nice weather.", "It shows the narrator likes to cry."] } }] },
        { "s": ["Wait.", "Was Priya actually stuck-up, or was she just scared, like I had been?", "How could I have been so sure about someone I had never even talked to?"],
          "stops": [{ "type": "tq", "at": 1, "alt": [2],
            "why": "The narrator asks herself hard questions about how she has treated Priya.",
            "note": { "a": "Will the narrator change her mind about Priya and try to be her friend?", "wrong": ["What is Priya's favorite color?", "When is the next science test?"] } }] },
        { "s": ["That night I told my grandma the whole story.", "Grandma stopped knitting and looked at me over her glasses.", "\"Mija, everyone you meet is fighting a battle you know nothing about,\" she said.", "\"Be the person who asks, not the person who decides.\""],
          "stops": [{ "type": "ww", "at": 2, "alt": [3, 1],
            "why": "Grandma, who is older and wiser, gives serious advice.",
            "note": { "a": "Don't judge people before you know them. Ask and be kind.", "wrong": ["Learn how to knit.", "Always wear your glasses."] } }] },
        { "s": ["The next day at lunch, Leah stared at me like I had grown a second head.", "Instead of sitting at our usual table, I walked straight into the library and sat down across from Priya."],
          "stops": [{ "type": "cc", "at": 1, "alt": [0],
            "why": "The narrator didn't like Priya, but now she's choosing to sit with her. That's the opposite of what she's been doing.",
            "note": { "a": "Grandma's advice changed her. She's going to get to know Priya.", "wrong": ["The cafeteria was closed.", "She needed to borrow a library book."] } }] },
        { "s": ["\"Can I see your drawings?\" I asked.", "Priya looked surprised, then slowly slid the green sketchbook across the table.", "Page after page showed her old street, her old friends, and her old dog.", "That's when I realized Priya wasn't stuck-up at all.", "She was lonely, and I had been making it worse."],
          "stops": [{ "type": "aha", "at": 3, "alt": [4],
            "why": "The narrator suddenly realizes the truth about Priya.",
            "note": { "a": "She will treat Priya kindly, and they might become friends.", "wrong": ["She will tell Leah that Priya is mean.", "She will start drawing dogs."] } }], "early": [1] },
        { "s": ["Now Priya eats lunch with Leah and me every day.", "She's drawing a new page in her sketchbook.", "It's our street, with both of our houses in it."], "early": [1] }
      ]
    },
    {
      "id": "photo",
      "title": "The Perfect Shot",
      "blurb": "Marcus will do anything to win the photo contest, as long as it's perfect.",
      "bg": "pond",
      "paragraphs": [
        { "s": ["Marcus had one goal for the school photo contest: win it.", "He borrowed his uncle's fancy camera, and every day after school he hiked to Miller's Pond to find the perfect shot.", "\"Perfect is the only thing that wins,\" he told his little sister, Bella."], "early": [1, 2] },
        { "s": ["Bella tagged along every afternoon.", "She chattered, she chased frogs, and she always ended up muddy.", "Marcus shooed her away whenever she wandered in front of his lens.", "\"You're ruining the perfect shot!\" he snapped."], "early": [3] },
        { "s": ["By Thursday, Marcus had taken four hundred pictures of the pond, and he hated every one.", "The light was wrong, or the water was too still, or the ducks were facing the wrong way.", "Nothing was perfect."],
          "stops": [{ "type": "aa", "at": 2, "alt": [],
            "why": "The word \"perfect\" keeps showing up again and again.",
            "note": { "a": "Marcus's need to be perfect is his problem. It's keeping him from being happy.", "wrong": ["Perfect is the name of the pond.", "The author likes the letter P."] } }] },
        { "s": ["That evening, Marcus stomped into the kitchen and showed his uncle the pictures.", "Uncle Dev scrolled through them slowly.", "Then he said, \"Marcus, the best photographers don't chase perfect. They chase true.\"", "\"A photo is great when it makes people feel something.\""],
          "stops": [{ "type": "ww", "at": 2, "alt": [3],
            "why": "Uncle Dev, who is older and wiser, gives Marcus serious advice.",
            "note": { "a": "Real moments and feelings matter more than being perfect.", "wrong": ["Buy a more expensive camera.", "Make sure the ducks face the camera."] } }] },
        { "s": ["Marcus lay awake that night.", "What if he never found the perfect shot?", "And what if Uncle Dev was right, and he had been looking for the wrong thing all along?"],
          "stops": [{ "type": "tq", "at": 2, "alt": [1],
            "why": "Marcus asks himself difficult questions he can't answer yet.",
            "note": { "a": "Will Marcus change what he's looking for in a photo?", "wrong": ["Will Marcus get a new phone?", "What will Marcus have for breakfast?"] } }] },
        { "s": ["The next morning, he scrolled through the camera one more time and stopped on a picture he didn't remember taking.", "It was blurry.", "It was crooked.", "It showed Bella, covered in mud, laughing as a frog jumped out of her hands.", "Suddenly Marcus understood.", "This was the picture that made him feel something."],
          "stops": [{ "type": "aha", "at": 4, "alt": [5],
            "why": "Marcus suddenly understands what his uncle meant.",
            "note": { "a": "Marcus will enter the real, imperfect photo instead of chasing a perfect one.", "wrong": ["Marcus will delete all his photos.", "Bella will take over the contest."] } }] },
        { "s": ["The photo reminded him of a day two summers ago, before he cared about contests.", "He and Bella had spent the whole afternoon catching frogs at that same pond, laughing so hard they fell in the water.", "He hadn't thought about that day in a long time."],
          "stops": [{ "type": "mm", "at": 0, "alt": [1],
            "why": "The story pauses so Marcus can remember a day from two summers ago.",
            "note": { "a": "It reminds Marcus what really matters to him: having fun with his sister.", "wrong": ["It explains how to catch frogs.", "It shows that the pond is deep."] } }] },
        { "s": ["On Friday, Marcus walked into the contest room with the blurry photo.", "His friend Tyler stared at it.", "\"Marcus, that's crooked. You always say perfect is the only thing that wins.\"", "Marcus just shrugged and hung it on the wall."],
          "stops": [{ "type": "cc", "at": 3, "alt": [0],
            "why": "Marcus always said only perfect wins, but now he proudly enters a crooked, blurry photo.",
            "note": { "a": "He has changed. He cares more about a true moment than being perfect now.", "wrong": ["He ran out of time to pick a different photo.", "He wants Tyler to lose."] } }], "early": [2] },
        { "s": ["Marcus didn't win first place.", "He won the People's Choice ribbon, because everyone who walked by the photo of Bella stopped and smiled.", "Bella hung the ribbon on her bedroom wall, right next to the photo."] }
      ]
    }
  ],

  "speed": [
    { "text": "Leo, who has bragged about his skateboard all year, suddenly gives it away to a kid he doesn't even know.", "answer": "cc" },
    { "text": "Tess always finishes her homework first. Today she rips her worksheet in half and walks out.", "answer": "cc" },
    { "text": "Elsa hid her ice powers for years. Alone on the mountain, she shows them off on purpose.", "answer": "cc" },
    { "text": "The class bully, who never talks to anyone, quietly offers the new kid half of his sandwich.", "answer": "cc" },
    { "text": "Dad, who says he hates dogs, comes home from work holding a puppy.", "answer": "cc" },
    { "text": "Kai, the loudest kid in class, doesn't say a single word all day.", "answer": "cc" },

    { "text": "Holding the torn map up to the window, Rosa finally figured out where the treasure was buried.", "answer": "aha" },
    { "text": "That's when Ben understood: his brother hadn't been ignoring him. He'd been planning Ben's surprise party.", "answer": "aha" },
    { "text": "Joy finally realizes that Riley needs Sadness, too.", "answer": "aha" },
    { "text": "It hit me all at once. I didn't lose the race because I was slow. I lost because I gave up.", "answer": "aha" },
    { "text": "Staring at the muddy footprints, the detective suddenly knew who had taken the cookies.", "answer": "aha" },
    { "text": "Mia finally understood that being brave doesn't mean you aren't scared.", "answer": "aha" },

    { "text": "Coach Ruiz pulled Ana aside. \"Winning is nice, but how you treat your team is what people remember.\"", "answer": "ww" },
    { "text": "Rafiki tells Simba, \"The past can hurt. But you can either run from it, or learn from it.\"", "answer": "ww" },
    { "text": "Grandpa set down his fork. \"Son, a person is only as good as his word.\"", "answer": "ww" },
    { "text": "The librarian knelt beside Jake. \"Every reader gets stuck. The trick is to keep turning pages.\"", "answer": "ww" },
    { "text": "Old Mr. Lee told Kim, \"Don't be afraid to fail. Be afraid of never trying.\"", "answer": "ww" },
    { "text": "Mom sat on the edge of my bed. \"Real friends tell you the truth, even when it's hard to hear.\"", "answer": "ww" },

    { "text": "Should I tell the teacher what I saw, even if my best friend gets in trouble?", "answer": "tq" },
    { "text": "Sam stared at the ceiling. How could he ever face his team after missing that goal?", "answer": "tq" },
    { "text": "Who am I supposed to be if I'm not the fastest runner anymore?", "answer": "tq" },
    { "text": "Lily wondered, \"Why does everyone leave? Is it something about me?\"", "answer": "tq" },
    { "text": "What would happen to the family farm if Dad couldn't work anymore?", "answer": "tq" },
    { "text": "Should I move to Mom's house in Texas, or stay here with Dad and my friends?", "answer": "tq" },

    { "text": "For the third time in the story, a black crow lands on the fence outside Ella's window.", "answer": "aa" },
    { "text": "Dory keeps saying \"Just keep swimming\" every time things get hard.", "answer": "aa" },
    { "text": "Every chapter ends with Max looking at the same faded photo of his dad.", "answer": "aa" },
    { "text": "Once again, someone mentions the old bridge that nobody is allowed to cross.", "answer": "aa" },
    { "text": "Once more, Grandma hums the same little song while she cooks.", "answer": "aa" },
    { "text": "It rained the day they moved, it rained the day of the big game, and now it's raining again.", "answer": "aa" },

    { "text": "As Carl sits in his quiet house, the story flashes back to his years with Ellie.", "answer": "mm" },
    { "text": "The smell of cinnamon took me back to Saturday mornings baking with Grandma when I was five.", "answer": "mm" },
    { "text": "Before the big game, Jay remembered the first time his dad taught him to throw a ball in the backyard.", "answer": "mm" },
    { "text": "Years ago, the story explains, a fire burned down the town's old school.", "answer": "mm" },
    { "text": "Holding the necklace, Nia remembered the day her mother gave it to her at the airport.", "answer": "mm" },
    { "text": "I thought back to my first day of kindergarten, when I hid under the table all morning.", "answer": "mm" }
  ]
};
