// ==================== AUDIO MANAGER ====================
// Music (Lyria 3), SFX (ElevenLabs), and voice lines (Cartesia) generated by
// scripts/generate_assets.py. Voice falls back to browser speech if a file is missing.

const AUDIO_BASE = '../assets/audio/hudson-river-rush';

class AudioManager {
  constructor() {
    this.music = {};
    this.currentMusic = null;
    this.musicVolume = 0.35;
    this.sfxVolume = 0.7;
    this.voiceVolume = 1.0;
    this.musicEnabled = true;
    this.sfxEnabled = true;
    this.voiceEnabled = true;
    this.sfxPool = {};
    this.voiceEl = null;
    this.missingVoice = new Set();
    this.unlocked = false;
  }

  unlock() {
    if (this.unlocked) return;
    this.unlocked = true;
    ['menu', 'river', 'dock', 'boss', 'victory'].forEach(key => {
      const el = new Audio(`${AUDIO_BASE}/music/${key}.mp3`);
      el.preload = 'auto';
      el.loop = key !== 'victory';
      el.volume = this.musicVolume;
      this.music[key] = el;
    });
    ['steer', 'correct', 'wrong', 'coin', 'splash', 'horn', 'boost', 'leg_done', 'snow'].forEach(key => {
      this.sfxPool[key] = [0, 1, 2].map(() => {
        const el = new Audio(`${AUDIO_BASE}/sfx/${key}.mp3`);
        el.preload = 'auto';
        return el;
      });
    });
    if (this.pendingMusic) this.playMusic(this.pendingMusic);
  }

  playMusic(key) {
    if (!this.unlocked) { this.pendingMusic = key; return; }
    const el = this.music[key];
    if (!el) return;
    if (this.currentMusic === key && !el.paused) return;
    if (this.currentMusic && this.music[this.currentMusic] && this.currentMusic !== key) {
      this.music[this.currentMusic].pause();
    }
    this.currentMusic = key;
    if (!this.musicEnabled) return;
    el.currentTime = 0;
    el.volume = this._duckedVolume();
    el.play().catch(() => {});
  }

  stopMusic() {
    if (this.currentMusic && this.music[this.currentMusic]) this.music[this.currentMusic].pause();
  }

  toggleMusic() {
    this.musicEnabled = !this.musicEnabled;
    if (!this.musicEnabled) this.stopMusic();
    else if (this.currentMusic) {
      const el = this.music[this.currentMusic];
      if (el) el.play().catch(() => {});
    }
    return this.musicEnabled;
  }

  sfx(key, { volume = 1, rate = 1 } = {}) {
    if (!this.sfxEnabled || !this.unlocked) return;
    const pool = this.sfxPool[key];
    if (!pool) return;
    const el = pool.find(a => a.paused || a.ended) || pool[0];
    try {
      el.currentTime = 0;
      el.volume = Math.min(1, this.sfxVolume * volume);
      el.playbackRate = rate;
      el.play().catch(() => {});
    } catch (_) {}
  }

  _duckedVolume() {
    const speaking = this.voiceEl && !this.voiceEl.paused;
    return speaking ? this.musicVolume * 0.35 : this.musicVolume;
  }

  _applyDuck() {
    const el = this.currentMusic && this.music[this.currentMusic];
    if (el) el.volume = this._duckedVolume();
  }

  stopVoice() {
    if (this.voiceEl) { this.voiceEl.pause(); this.voiceEl = null; }
    if (window.speechSynthesis) window.speechSynthesis.cancel();
    this._applyDuck();
  }

  // key = voice file basename (e.g. 'q_h1'); text = fallback for browser speech.
  say(key, text) {
    if (!this.voiceEnabled) return;
    this.stopVoice();
    if (key && !this.missingVoice.has(key)) {
      const el = new Audio(`${AUDIO_BASE}/voice/${key}.mp3`);
      el.volume = this.voiceVolume;
      this.voiceEl = el;
      el.onended = () => { if (this.voiceEl === el) this.voiceEl = null; this._applyDuck(); };
      el.onerror = () => {
        this.missingVoice.add(key);
        if (this.voiceEl === el) { this.voiceEl = null; this._speakFallback(text); }
      };
      el.play().then(() => this._applyDuck()).catch(() => {});
      return;
    }
    this._speakFallback(text);
  }

  _speakFallback(text) {
    if (!text || !window.speechSynthesis) return;
    const u = new SpeechSynthesisUtterance(text);
    u.rate = 0.95;
    u.pitch = 1.05;
    window.speechSynthesis.speak(u);
  }
}
